# Generated by Django 5.0.1 on 2024-03-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_document',
            field=models.FileField(blank=True, upload_to='Jobs'),
        ),
    ]
