# Generated by Django 4.2.7 on 2024-04-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_description_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On Site')], max_length=100),
        ),
    ]
