# Generated by Django 4.2.7 on 2024-04-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='candidate',
            new_name='candidate_id',
        ),
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='job',
            new_name='job_id',
        ),
    ]
