# Generated by Django 4.2.7 on 2024-04-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_rename_candidate_appliedjobs_candidate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter',
            new_name='recruiter_id',
        ),
    ]
