# Generated by Django 4.2.7 on 2024-04-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_rename_recruiter_job_recruiter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter_id',
            new_name='recruiter',
        ),
    ]
