# Generated by Django 4.2.7 on 2024-04-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_rename_recruiter_id_job_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='job_id',
            new_name='job',
        ),
    ]
