# Generated by Django 4.2.7 on 2024-04-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_remove_appliedjobs_avg_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='avg_score',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='description_score',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='domain_score',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='education_score',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='experience_score',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='skills_score',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
