# Generated by Django 4.0 on 2024-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
