# Generated by Django 5.0.1 on 2024-05-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_message_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
    ]
